In [1]:
import numpy as np


## 1. Write a NumPy program to create an array of all even integers from 30 to 70.

In [12]:

# Create an array of given even integers
integers_array = np.arange(30, 71, 2)

print("Array of give integers:", integers_array)


Array of give integers: [30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


## 2. Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.

In [13]:

# Create an array of 15 random numbers from a standard normal distribution
random_numbers = np.random.randn(15)

print("Array of random numbers from a standard normal distribution:", random_numbers)


Array of random numbers from a standard normal distribution: [ 1.04686202  1.19116094  0.10966888 -1.93099993  0.05827169  0.49594487
 -1.41716297 -1.60779924 -0.32341828 -0.09406603 -0.8786472  -1.01919434
 -0.40924005 -1.3539481   0.77814314]


## 3. How to compute the cross-product of two matrices in NumPy.

In [9]:

# Define two vectors
vector1 = np.array([8, 1, 5])
vector2 = np.array([7, 4, 2])

# Compute the cross-product
cross_product = np.cross(vector1, vector2)

print("Cross-product of the vectors:", cross_product)


Cross-product of the vectors: [-18  19  25]


## 4. How to compute the determinant of an array using NumPy.

In [10]:

# Create an array
given_array = np.array([[5, 9], [3, 8]])

# Compute the determinant
determinant = np.linalg.det(given_array)

print("Determinant of the array:", determinant)


Determinant of the array: 12.999999999999995


## 5. How to create a 3x3x3 array with random values using NumPy.

In [6]:

# Create an array with random values
random_array = np.random.rand(3, 3, 3)

print("Array of 3x3x3:", random_array)


Array of 3x3x3: [[[0.25463334 0.91921953 0.76530183]
  [0.80234395 0.40282816 0.65670204]
  [0.65671659 0.21741402 0.57169279]]

 [[0.29968378 0.93644983 0.41801225]
  [0.81004886 0.86859185 0.62539802]
  [0.19532147 0.26080229 0.40937046]]

 [[0.85091258 0.25770439 0.08049878]
  [0.327745   0.62792704 0.94203493]
  [0.49011613 0.62894091 0.3357466 ]]]


## 6. How to create a 5x5 array with random values and find the minimum and maximum values using NumPy.

In [7]:

# Create an array with random values
random_array = np.random.rand(5, 5)
print("Array of 5x5:", random_array)

# Find the minimum values in the array
min_value = np.min(random_array)
print("Minimum value:", min_value)

# Find the maximum values in the array
max_value = np.max(random_array)
print("Maximum value:", max_value)


Array of 5x5: [[0.89074965 0.19909491 0.19573659 0.08697397 0.07892454]
 [0.59815338 0.20422169 0.77782779 0.49130073 0.32742683]
 [0.22721645 0.2798946  0.48507825 0.30134428 0.77596523]
 [0.21728982 0.24675068 0.12054336 0.1096231  0.03808792]
 [0.27275423 0.2027374  0.05268472 0.73158458 0.20869213]]
Minimum value: 0.03808792265227412
Maximum value: 0.8907496523046061


## 7. How to compute the mean, standard deviation, and variance of a given array along the second axis in NumPy.

In [14]:

given_array = np.array([[1, 2, 3], [4, 5, 6]])

# Compute the mean along the second axis
mean_of_array = np.mean(given_array, axis=1)
print("Mean along the second axis:", mean_of_array)

# Compute the standard deviation along the second axis
stdeviation_of_array = np.std(given_array, axis=1)
print("Standard deviation along the second axis:", stdeviation_of_array)

# Compute the variance along the second axis
variance_of_array = np.var(given_array, axis=1)
print("Variance along the second axis:", variance_of_array)


Mean along the second axis: [2. 5.]
Standard deviation along the second axis: [0.81649658 0.81649658]
Variance along the second axis: [0.66666667 0.66666667]
